module Kitchen
  module Driver
    module Helpers
      # Return a newline-delimited string containing zonecfg subcommands
      # required to create a new zone.
      # Expects a hash for format arguments that will be used to replace
      # sprintf-type name references.
      def zone_config_commands(format_args = {})
        subcommands = %q(create -b
          set brand=solaris
          set zonepath=%{zone_path}
          set autoboot=true
          set bootargs="-m verbose"
          set autoshutdown=shutdown
          set ip-type=exclusive
          add anet
          set lower-link=%{zone_lower_link}
          set configure-allowed-address=true
          set link-protection=mac-nospoof
          set mac-address=auto
          end
          add attr
          set name=comment
          set type=string
          set value="%{zone_comment}"
          end
        ).gsub(/^\s+/, '') # strip leading spaces
        # TODO: Add error handling (i.e. missing format arguments).
        subcommands % format_args
      end

      # Return a newline-delimited string containing the XML required to
      # represent a System Configuration profile to be used to configure
      # a zone.
      # Expects a hash for format arguments that will be used to replace
      # sprintf-type name references.
      def zone_sc_profile(format_args = {})
        profile = %q(<?xml version='1.0' encoding='US-ASCII'?>
<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
<!-- Auto-generated by sysconfig -->
<service_bundle type="profile" name="sysconfig">
  <service version="1" type="service" name="system/identity">
    <instance enabled="true" name="node">
      <property_group type="application" name="config">
        <propval type="astring" name="nodename" value="%{zone_name}"/>
      </property_group>
    </instance>
  </service>
  <service version="1" type="service" name="network/physical">
    <instance enabled="true" name="default">
      <property_group type="application" name="netcfg">
        <propval type="astring" name="active_ncp" value="Automatic"/>
      </property_group>
    </instance>
  </service>
  <service version="1" type="service" name="system/name-service/switch">
    <property_group type="application" name="config">
      <propval type="astring" name="default" value="files"/>
    </property_group>
    <instance enabled="true" name="default"/>
  </service>
  <service version="1" type="service" name="system/name-service/cache">
    <instance enabled="true" name="default"/>
  </service>
  <service version="1" type="service" name="system/keymap">
    <instance enabled="true" name="default">
      <property_group type="application" name="keymap">
        <propval type="astring" name="layout" value="US-English"/>
      </property_group>
    </instance>
  </service>
  <service version="1" type="service" name="system/environment">
    <instance enabled="true" name="init">
      <property_group type="application" name="environment">
        <propval type="astring" name="LANG" value="en_US.UTF-8"/>
      </property_group>
    </instance>
  </service>
  <service version="1" type="service" name="system/timezone">
    <instance enabled="true" name="default">
      <property_group type="application" name="timezone">
        <propval type="astring" name="localtime" value="UTC"/>
      </property_group>
    </instance>
  </service>
  <service version="1" type="service" name="system/config-user">
    <instance enabled="true" name="default">
      <property_group type="application" name="root_account">
        <propval type="astring" name="type" value="normal"/>
        <propval type="astring" name="login" value="root"/>
        <propval type="astring" name="password" value="$5$aWNw9QMt$6165ba2732e1acd1892edcc296e0e5d59b3c610eab47b3d006b6416fb169d7c1"/>
      </property_group>
      <property_group type="application" name="user_account">
        <propval type="astring" name="shell" value="/usr/bin/bash"/>
        <propval type="astring" name="login" value="%{kitchen_user_name}"/>
        <propval type="astring" name="password" value="NP"/>
        <propval type="astring" name="type" value="normal"/>
        <propval type="astring" name="sudoers" value="ALL=(ALL) NOPASSWD: ALL"/>
        <propval type="count" name="gid" value="10"/>
        <propval type="astring" name="description" value="kitchen"/>
        <propval type="astring" name="profiles" value="System Administrator"/>
        <property type="astring" name="ssh_public_keys">
          <astring_list>
              <value_node value="%{ssh_public_key}"/>
          </astring_list>
       </property>
      </property_group>
    </instance>
  </service>
</service_bundle>)
        # TODO: Add error handling (i.e. missing format arguments).
        profile % format_args
      end
    end
  end
end
